# -------------------------------------------------------
#!/bin/bash
# -------------------------------------------------------
# Copyright (c) [2022] Nadege LEMPERIERE
# All rights reserved
# -------------------------------------------------------
# Release pipeline for FLL common tools
# -------------------------------------------------------
# Nadège LEMPERIERE, @19 october 2022
# Latest revision: 19 october 2022
# -------------------------------------------------------

name: Keywords Release Pipeline

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container:
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://technogix/terraform-python-awscli:v2.0.0
              with:
                args: pip install -r requirements-test.txt --target site-packages

            - name: Linting module
              uses: docker://technogix/terraform-python-awscli:v2.0.0
              with:
                args: pylint commons

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/python@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                PYTHONPATH: /github/workspace/site-packages
              with:
                args: --sarif-file-output=snyk.sarif --file=setup.py

            - name: Run pip-audit to check for vulnerabilities
              uses: docker://technogix/terraform-python-awscli:v2.0.0
              with:
                args: pip-audit -r requirements-test.txt --format json

            - name: Upload snyk result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: snyk.sarif